# Generated by Django 4.2.5 on 2023-09-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Контактный email')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.CharField(blank=True, choices=[('09:00', '09:00'), ('18:00', '18:00')], max_length=5, null=True, verbose_name='Время начала')),
                ('time_end', models.CharField(blank=True, choices=[('09:00', '09:00'), ('18:00', '18:00')], max_length=5, null=True, verbose_name='Время окончания')),
                ('frequency', models.CharField(choices=[('D', 'Раз в день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц')], max_length=1, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('C', 'Завершена'), ('N', 'Создана'), ('R', 'Запущена')], max_length=1, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'настройка рассылки',
                'verbose_name_plural': 'настройка рассылки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skychimp.client')),
                ('mailing_setting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='skychimp.mailingsetting')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема сообщения')),
                ('body', models.TextField(verbose_name='Тело сообщения')),
                ('mailing_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='skychimp.mailingsetting')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='clients',
            field=models.ManyToManyField(related_name='mailingsetting', through='skychimp.Subscription', to='skychimp.client'),
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_datetime', models.DateTimeField(verbose_name='Дата и время последней попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('status', models.CharField(choices=[('C', 'Завершена'), ('O', 'Создана'), ('R', 'Запущена')], max_length=1)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='skychimp.client')),
                ('mailing_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='skychimp.mailingsetting')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылки',
            },
        ),
    ]
