# Generated by Django 4.2.5 on 2023-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skychimp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(choices=[('C', 'Завершена'), ('N', 'Создана'), ('R', 'Запущена')], max_length=1),
        ),
    ]
